name: Docs

on:
  push:
    branches: main
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash -l {0}

permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476  # v3.0.0
        with:
          environment-file: docs/build-environment.yml

      - name: Build
        run: sphinx-build . output
        working-directory: docs
